name: Security SAST

on:
  push:
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            config: "p/javascript p/nodejs" #p/owasp-top-ten

      - name: Run Semgrep
        run: |
          docker run --rm \
            -v "${PWD}:/src" \
            semgrep/semgrep \
            semgrep scan \
            --config=auto \
            --exclude=node_modules \
            --exclude=compiled \
            --exclude=dist \
            --exclude=vendor \
            --exclude=lib-bowser.js \
            /src

      - name: Upload Semgrep Results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json
